### ISSUE TITLE
Improve register allocation for Virgil

### ISSUE THREAD

**Issue by k-sareen** [titzer/virgil#35] opened 2020-11-24 02:36 UTC
Issue for tracking implementation of a graph-coloring based register allocation for Virgil with both spilling and splitting of live ranges. The splitting heuristic implemented should be cheap to compute and should not sacrifice the quality of allocation. A simple splitting heuristic is implemented in the V8 optimizing JS compiler.

The main concern with a graph-coloring approach is the cost of rebuilding the interference graph after splitting or spilling a live range. Ideally, the interference graph reconstruction is cheap. An approach like the tiling based approach of Callahan-Koblenz [1] can be considered.

### Current Roadmap
- [ ]  Rip out liveness analysis from current register allocator
- [ ]  Interference graph construction and graph coloring (with spilling)
- [ ]  Refine splitting heuristic

---
[1]: Callahan, David, and Brian Koblenz. “Register Allocation via Hierarchical Graph Coloring.” Proceedings of the ACM SIGPLAN 1991 Conference on Programming Language Design and Implementation, vol. 26, no. 6, 1991, pp. 192–203.

**Comment by k-sareen** [comment] 2021-01-11 05:12
Apologies for the radio silence: have been quite busy with IRL stuff like moving etc. At this point I've lost a bit of context surrounding the entire plan :frowning:. As a refresher: first step is ripping the liveness (i.e. don't build intervals) from the current `IntervalBuilder`? Did we decide on how it fits into the current ecosystem, or should it be kept entirely separate?

**Comment by titzer** [comment] 2021-02-08 23:10
There are at least two moving parts here. To avoid making the new allocator depend on bringing up a new backend using the new backend framework, the allocator should work with the existing X86CodeGen. But the new allocator should be aimed to work with the new backend framework too, since I want to rewrite the existing backend with the new backend framework eventually. So the new allocator needs to have two "frontends" that can process IR from the two different kinds of backends.

The old backend did not compute liveness at all; the register allocator filled out the liveness bitmatrix (block x var). The linear scan allocator computes this matrix as it goes. The new backend computes the liveness bitmatrix incrementally during instruction selection (it in fact does this in order to do simple dead code elimination as it goes).

So I think it makes sense to copy out the part of the current regalloc that fills out this bitmatrix, so that it is always available when regalloc starts. Then you can process the code one basic block at a time in the new allocator, e.g. to build the exact interference graph.

**Comment by k-sareen** [comment] 2021-02-17 11:52
More specifically is the idea that we want the LSRA `assignRegs()` method to calculate the liveness bitmatrix and then pass it onto the `IntervalBuilder`? Would that not result in sort of redundantly going over the blocks twice: once for the liveness bitmatrix and once for building the intervals using the bitmatrix?

**Comment by k-sareen** [comment] 2021-09-02 04:33
Ah -- I was also doing the same in my free time. I had lost track of the backend so was getting used to the new one again. Sorry for being AWOL for so long.

**Comment by titzer** [comment] 2022-03-12 18:28
At this point, I have completed the local register allocator and plan to turn it on by default for the next stable release.

**Comment by titzer** [comment] 2023-08-20 15:04
Well, I haven't been using the issue tracker as intended, but @s123unny implemented a graph coloring register allocator that is activated by -O2 now.

**Comment by titzer** [comment] 2024-04-06 15:13
I'm going to close this as the graph-coloring register allocator is pretty stable, running in CI at -O2.

**Closed by titzer** 2024-04-06 15:13 UTC
Labels: enhancement
